"""
SmartAgro Backend — SKUAST-K Spray Lookup Database
Static spray data for all 16 Kashmir apple growth stages.
Source: SKUAST-K 2025 & 2026 Apple Spray Schedule Guidelines
This file seeds the spray_lookup table in SQLite on first run.
"""

SPRAY_DB = [
    {
        "id": 1,
        "growth_stage":  "Delayed Dormancy",
        "spray_name":    "Horticultural Mineral Oil",
        "spray_type":    "Insecticide",
        "dosage":        "2 L / 100 L water",
        "best_window":   "6 AM – 9 AM",
        "interval":      21,
        "target":        "San Jose Scale, Wooly Aphid, overwintering eggs",
        "caution":       "Do not spray if temperature is below 4°C. Do not mix with sulfur.",
        "source":        "SKUAST-K 2026",
    },
    {
        "id": 2,
        "growth_stage":  "Green Tip",
        "spray_name":    "Mancozeb 75% WP",
        "spray_type":    "Fungicide",
        "dosage":        "300 g / 100 L water",
        "best_window":   "6 AM – 9 AM",
        "interval":      14,
        "target":        "Apple Scab, Early Blight",
        "caution":       "Avoid spraying during flowering. Wear protective gear.",
        "source":        "SKUAST-K 2026",
    },
    {
        "id": 3,
        "growth_stage":  "Tight Cluster",
        "spray_name":    "Propineb 70% WP",
        "spray_type":    "Fungicide",
        "dosage":        "300 g / 100 L water",
        "best_window":   "6 AM – 9 AM",
        "interval":      14,
        "target":        "Apple Scab, Powdery Mildew",
        "caution":       "Do not apply within 7 days of harvest. Avoid contact with eyes.",
        "source":        "SKUAST-K 2026",
    },
    {
        "id": 4,
        "growth_stage":  "Pink Bud",
        "spray_name":    "Dodine 65% WP",
        "spray_type":    "Fungicide",
        "dosage":        "60 g / 100 L water",
        "best_window":   "6 AM – 9 AM",
        "interval":      14,
        "target":        "Apple Scab (primary infection)",
        "caution":       "Do not apply more than 3 times per season. Highly phytotoxic if overdosed.",
        "source":        "SKUAST-K 2026",
    },
    {
        "id": 5,
        "growth_stage":  "Flowering",
        "spray_name":    "Mancozeb 75% WP",
        "spray_type":    "Fungicide",
        "dosage":        "300 g / 100 L water",
        "best_window":   "6 AM – 7 AM",
        "interval":      10,
        "target":        "Apple Scab (need-based only)",
        "caution":       "CRITICAL — Apply only if disease pressure is very high. Risk of bee toxicity. Spray at dawn before bees are active.",
        "source":        "SKUAST-K 2026",
    },
    {
        "id": 6,
        "growth_stage":  "Petal Fall",
        "spray_name":    "Difenoconazole 25% EC",
        "spray_type":    "Fungicide",
        "dosage":        "30 ml / 100 L water",
        "best_window":   "6 AM – 9 AM",
        "interval":      14,
        "target":        "Apple Scab, Alternaria Leaf Spot",
        "caution":       "Wear full protective clothing. Do not reuse spray equipment without cleaning.",
        "source":        "SKUAST-K 2026",
    },
    {
        "id": 7,
        "growth_stage":  "Fruitlet",
        "spray_name":    "Captan 50% WP",
        "spray_type":    "Fungicide",
        "dosage":        "300 g / 100 L water",
        "best_window":   "6 AM – 9 AM",
        "interval":      14,
        "target":        "Apple Scab, Fruit Rot",
        "caution":       "Do not apply in temperatures above 32°C. PHI: 7 days.",
        "source":        "SKUAST-K 2026",
    },
    {
        "id": 8,
        "growth_stage":  "Fruit Set",
        "spray_name":    "Zineb + Hexaconazole 72% WP",
        "spray_type":    "Fungicide",
        "dosage":        "125 g / 100 L water",
        "best_window":   "6 AM – 9 AM",
        "interval":      14,
        "target":        "Apple Scab, Powdery Mildew, Brown Rot",
        "caution":       "Keep out of reach of children. Store in cool, dry place.",
        "source":        "SKUAST-K 2026",
    },
    {
        "id": 9,
        "growth_stage":  "Fruit Development-I",
        "spray_name":    "Captan 50% WP",
        "spray_type":    "Fungicide",
        "dosage":        "300 g / 100 L water",
        "best_window":   "6 AM – 9 AM",
        "interval":      14,
        "target":        "Apple Scab, Fruit Rot, Sooty Blotch",
        "caution":       "PHI: 7 days. Do not mix with alkaline pesticides.",
        "source":        "SKUAST-K 2026",
    },
    {
        "id": 10,
        "growth_stage":  "Fruit Development-II",
        "spray_name":    "Trifloxystrobin + Tebuconazole 75% WG",
        "spray_type":    "Fungicide",
        "dosage":        "40 g / 100 L water",
        "best_window":   "6 AM – 9 AM",
        "interval":      14,
        "target":        "Apple Scab, Powdery Mildew, Rust",
        "caution":       "Max 2 applications per season to prevent resistance. PHI: 14 days.",
        "source":        "SKUAST-K 2026",
    },
    {
        "id": 11,
        "growth_stage":  "Fruit Development-III",
        "spray_name":    "Zineb 75% WP",
        "spray_type":    "Fungicide",
        "dosage":        "300 g / 100 L water",
        "best_window":   "6 AM – 9 AM",
        "interval":      14,
        "target":        "Apple Scab, Late Blight, Fruit Spot",
        "caution":       "Avoid spray drift onto other crops. PHI: 10 days.",
        "source":        "SKUAST-K 2026",
    },
    {
        "id": 12,
        "growth_stage":  "Fruit Development-IV",
        "spray_name":    "Myclobutanil 10% WP",
        "spray_type":    "Fungicide",
        "dosage":        "70 g / 100 L water",
        "best_window":   "6 AM – 9 AM",
        "interval":      14,
        "target":        "Powdery Mildew, Apple Scab",
        "caution":       "PHI: 14 days. Do not apply after colour development begins.",
        "source":        "SKUAST-K 2026",
    },
    {
        "id": 13,
        "growth_stage":  "Pre-Harvest",
        "spray_name":    "Captan 50% WP",
        "spray_type":    "Fungicide",
        "dosage":        "300 g / 100 L water",
        "best_window":   "6 AM – 9 AM",
        "interval":      14,
        "target":        "Fruit Rot, Sooty Blotch, Fly Speck",
        "caution":       "STRICT PHI: 7 days before harvest. Do not exceed recommended dose.",
        "source":        "SKUAST-K 2026",
    },
    {
        "id": 14,
        "growth_stage":  "Harvest",
        "spray_name":    "No Spray",
        "spray_type":    "None",
        "dosage":        "N/A",
        "best_window":   "N/A",
        "interval":      0,
        "target":        "N/A — Harvest period, no chemical application",
        "caution":       "DO NOT SPRAY during harvest. Risk of chemical residue on fruit.",
        "source":        "SKUAST-K 2026",
    },
    {
        "id": 15,
        "growth_stage":  "Post-Harvest",
        "spray_name":    "Chlorpyriphos 20% EC",
        "spray_type":    "Insecticide",
        "dosage":        "100 ml / 100 L water",
        "best_window":   "6 AM – 9 AM",
        "interval":      21,
        "target":        "Bark Beetles, San Jose Scale, Leaf Rollers",
        "caution":       "Highly toxic to aquatic organisms. Do not spray near water bodies.",
        "source":        "SKUAST-K 2026",
    },
    {
        "id": 16,
        "growth_stage":  "Dormancy",
        "spray_name":    "Copper Oxychloride 50% WP",
        "spray_type":    "Fungicide + Bactericide",
        "dosage":        "300 g / 100 L water",
        "best_window":   "6 AM – 9 AM",
        "interval":      21,
        "target":        "Canker, Bacterial Blight, overwintering fungal spores",
        "caution":       "Do not spray if rain is expected within 6 hours. Avoid copper accumulation in soil.",
        "source":        "SKUAST-K 2026",
    },
]